// packages/vue/src/ExcelViewer.vue
<template>
  <div ref="containerRef" class="excel-viewer-vue" :style="containerStyle"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, computed } from 'vue';
import { ExcelViewer } from '@ldesign/excel-viewer-core';
import type {
  ExcelViewerOptions,
  SheetData,
  ExportOptions,
  SearchOptions,
  SearchResult,
  SelectionRange,
} from '@ldesign/excel-viewer-core';

interface Props {
  /** 文件源（File 对象、ArrayBuffer 或 URL） */
  file?: File | ArrayBuffer | string;
  /** 是否显示工具栏 */
  showToolbar?: boolean;
  /** 是否显示公式栏 */
  showFormulaBar?: boolean;
  /** 是否显示表格标签 */
  showSheetTabs?: boolean;
  /** 是否允许编辑 */
  allowEdit?: boolean;
  /** 是否允许复制 */
  allowCopy?: boolean;
  /** 是否允许粘贴 */
  allowPaste?: boolean;
  /** 语言 */
  lang?: 'zh' | 'en';
  /** 主题 */
  theme?: 'light' | 'dark';
  /** 自定义样式 */
  customStyle?: string;
  /** 容器高度 */
  height?: string | number;
  /** 容器宽度 */
  width?: string | number;
}

const props = withDefaults(defineProps<Props>(), {
  showToolbar: true,
  showFormulaBar: true,
  showSheetTabs: true,
  allowEdit: true,
  allowCopy: true,
  allowPaste: true,
  lang: 'zh',
  theme: 'light',
  height: '600px',
  width: '100%',
});

interface Emits {
  (e: 'load', data: { status: string; sheets?: SheetData[] }): void;
  (e: 'loadError', error: any): void;
  (e: 'cellChange', data: { row: number; col: number; oldValue: any; newValue: any }): void;
  (e: 'cellClick', data: { sheetIndex: number; row: number; col: number; value: any }): void;
  (e: 'cellDoubleClick', data: { sheetIndex: number; row: number; col: number; value: any }): void;
  (e: 'selectionChange', range: SelectionRange): void;
  (e: 'sheetChange', data: { index: number }): void;
  (e: 'error', error: any): void;
}

const emit = defineEmits<Emits>();

const containerRef = ref<HTMLElement>();
let viewer: ExcelViewer | null = null;

const containerStyle = computed(() => {
  const style: Record<string, string> = {};
  
  if (typeof props.height === 'number') {
    style.height = `${props.height}px`;
  } else {
    style.height = props.height;
  }
  
  if (typeof props.width === 'number') {
    style.width = `${props.width}px`;
  } else {
    style.width = props.width;
  }
  
  return style;
});

/**
 * 初始化查看器
 */
const initViewer = () => {
  if (!containerRef.value) return;

  const options: ExcelViewerOptions = {
    container: containerRef.value,
    showToolbar: props.showToolbar,
    showFormulaBar: props.showFormulaBar,
    showSheetTabs: props.showSheetTabs,
    allowEdit: props.allowEdit,
    allowCopy: props.allowCopy,
    allowPaste: props.allowPaste,
    lang: props.lang,
    theme: props.theme,
    customStyle: props.customStyle,
    hooks: {
      afterLoad: (data) => {
        emit('load', { status: 'success', sheets: data });
      },
      onCellClick: (sheetIndex, row, col, value) => {
        emit('cellClick', { sheetIndex, row, col, value });
      },
      onCellDoubleClick: (sheetIndex, row, col, value) => {
        emit('cellDoubleClick', { sheetIndex, row, col, value });
      },
      onSelectionChange: (range) => {
        emit('selectionChange', range);
      },
      onError: (error) => {
        emit('error', error);
      },
    },
  };

  viewer = new ExcelViewer(options);

  // 绑定事件
  viewer.on('load', (data) => emit('load', data));
  viewer.on('loadError', (data) => emit('loadError', data.error));
  viewer.on('cellChange', (data) => emit('cellChange', data));
  viewer.on('sheetChange', (data) => emit('sheetChange', data));
  viewer.on('error', (data) => emit('error', data.error));
};

/**
 * 加载文件
 */
const loadFile = async (file: File | ArrayBuffer | string) => {
  if (!viewer) return;
  await viewer.loadFile(file);
};

/**
 * 获取数据
 */
const getData = (): SheetData[] => {
  return viewer?.getData() || [];
};

/**
 * 导出文件
 */
const exportFile = (options: ExportOptions): Blob | null => {
  return viewer?.exportFile(options) || null;
};

/**
 * 下载文件
 */
const downloadFile = (options: ExportOptions): void => {
  viewer?.downloadFile(options);
};

/**
 * 搜索
 */
const search = (options: SearchOptions): SearchResult[] => {
  return viewer?.search(options) || [];
};

/**
 * 获取选中区域
 */
const getSelection = (): SelectionRange | null => {
  return viewer?.getSelection() || null;
};

/**
 * 设置单元格值
 */
const setCellValue = (row: number, col: number, value: any): void => {
  viewer?.setCellValue(row, col, value);
};

/**
 * 获取单元格值
 */
const getCellValue = (row: number, col: number): any => {
  return viewer?.getCellValue(row, col);
};

/**
 * 切换工作表
 */
const setActiveSheet = (index: number): void => {
  viewer?.setActiveSheet(index);
};

/**
 * 撤销
 */
const undo = (): void => {
  viewer?.undo();
};

/**
 * 重做
 */
const redo = (): void => {
  viewer?.redo();
};

/**
 * 刷新
 */
const refresh = (): void => {
  viewer?.refresh();
};

// 监听文件变化
watch(() => props.file, async (newFile) => {
  if (newFile && viewer) {
    await loadFile(newFile);
  }
});

onMounted(() => {
  initViewer();
  
  // 如果有初始文件，加载它
  if (props.file && viewer) {
    loadFile(props.file);
  }
});

onBeforeUnmount(() => {
  if (viewer) {
    viewer.destroy();
    viewer = null;
  }
});

// 暴露方法给父组件
defineExpose({
  loadFile,
  getData,
  exportFile,
  downloadFile,
  search,
  getSelection,
  setCellValue,
  getCellValue,
  setActiveSheet,
  undo,
  redo,
  refresh,
});
</script>

<style scoped>
.excel-viewer-vue {
  position: relative;
  overflow: hidden;
}
</style>

// packages/react/src/ExcelViewer.tsx
/**
 * Excel Viewer React 组件
 */

import React, { useRef, useEffect, useImperativeHandle, forwardRef } from 'react';
import { ExcelViewer as CoreViewer } from '@ldesign/excel-viewer-core';
import type {
  ExcelViewerOptions,
  SheetData,
  ExportOptions,
  SearchOptions,
  SearchResult,
  SelectionRange,
} from '@ldesign/excel-viewer-core';

export interface ExcelViewerProps {
  /** 文件源（File 对象、ArrayBuffer 或 URL） */
  file?: File | ArrayBuffer | string;
  /** 是否显示工具栏 */
  showToolbar?: boolean;
  /** 是否显示公式栏 */
  showFormulaBar?: boolean;
  /** 是否显示表格标签 */
  showSheetTabs?: boolean;
  /** 是否允许编辑 */
  allowEdit?: boolean;
  /** 是否允许复制 */
  allowCopy?: boolean;
  /** 是否允许粘贴 */
  allowPaste?: boolean;
  /** 语言 */
  lang?: 'zh' | 'en';
  /** 主题 */
  theme?: 'light' | 'dark';
  /** 自定义样式 */
  customStyle?: string;
  /** 容器高度 */
  height?: string | number;
  /** 容器宽度 */
  width?: string | number;
  /** 类名 */
  className?: string;
  /** 样式 */
  style?: React.CSSProperties;
  
  // 事件回调
  onLoad?: (data: { status: string; sheets?: SheetData[] }) => void;
  onLoadError?: (error: any) => void;
  onCellChange?: (data: { row: number; col: number; oldValue: any; newValue: any }) => void;
  onCellClick?: (data: { sheetIndex: number; row: number; col: number; value: any }) => void;
  onCellDoubleClick?: (data: { sheetIndex: number; row: number; col: number; value: any }) => void;
  onSelectionChange?: (range: SelectionRange) => void;
  onSheetChange?: (data: { index: number }) => void;
  onError?: (error: any) => void;
}

export interface ExcelViewerRef {
  loadFile: (file: File | ArrayBuffer | string) => Promise<void>;
  getData: () => SheetData[];
  exportFile: (options: ExportOptions) => Blob | null;
  downloadFile: (options: ExportOptions) => void;
  search: (options: SearchOptions) => SearchResult[];
  getSelection: () => SelectionRange | null;
  setCellValue: (row: number, col: number, value: any) => void;
  getCellValue: (row: number, col: number) => any;
  setActiveSheet: (index: number) => void;
  undo: () => void;
  redo: () => void;
  refresh: () => void;
}

export const ExcelViewer = forwardRef<ExcelViewerRef, ExcelViewerProps>((props, ref) => {
  const {
    file,
    showToolbar = true,
    showFormulaBar = true,
    showSheetTabs = true,
    allowEdit = true,
    allowCopy = true,
    allowPaste = true,
    lang = 'zh',
    theme = 'light',
    customStyle,
    height = '600px',
    width = '100%',
    className,
    style,
    onLoad,
    onLoadError,
    onCellChange,
    onCellClick,
    onCellDoubleClick,
    onSelectionChange,
    onSheetChange,
    onError,
  } = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const viewerRef = useRef<CoreViewer | null>(null);

  // 初始化查看器
  useEffect(() => {
    if (!containerRef.current) return;

    const options: ExcelViewerOptions = {
      container: containerRef.current,
      showToolbar,
      showFormulaBar,
      showSheetTabs,
      allowEdit,
      allowCopy,
      allowPaste,
      lang,
      theme,
      customStyle,
      hooks: {
        afterLoad: (data) => {
          onLoad?.({ status: 'success', sheets: data });
        },
        onCellClick: (sheetIndex, row, col, value) => {
          onCellClick?.({ sheetIndex, row, col, value });
        },
        onCellDoubleClick: (sheetIndex, row, col, value) => {
          onCellDoubleClick?.({ sheetIndex, row, col, value });
        },
        onSelectionChange: (range) => {
          onSelectionChange?.(range);
        },
        onError: (error) => {
          onError?.(error);
        },
      },
    };

    const viewer = new CoreViewer(options);
    viewerRef.current = viewer;

    // 绑定事件
    viewer.on('load', (data) => onLoad?.(data));
    viewer.on('loadError', (data) => onLoadError?.(data.error));
    viewer.on('cellChange', (data) => onCellChange?.(data));
    viewer.on('sheetChange', (data) => onSheetChange?.(data));
    viewer.on('error', (data) => onError?.(data.error));

    return () => {
      viewer.destroy();
      viewerRef.current = null;
    };
  }, []); // 只在挂载时初始化一次

  // 监听配置变化（不重新创建实例）
  useEffect(() => {
    // 这里可以添加动态配置更新逻辑
  }, [
    showToolbar,
    showFormulaBar,
    showSheetTabs,
    allowEdit,
    allowCopy,
    allowPaste,
    lang,
    theme,
    customStyle,
  ]);

  // 加载文件
  useEffect(() => {
    if (file && viewerRef.current) {
      viewerRef.current.loadFile(file);
    }
  }, [file]);

  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    loadFile: async (file: File | ArrayBuffer | string) => {
      if (viewerRef.current) {
        await viewerRef.current.loadFile(file);
      }
    },
    getData: () => {
      return viewerRef.current?.getData() || [];
    },
    exportFile: (options: ExportOptions) => {
      return viewerRef.current?.exportFile(options) || null;
    },
    downloadFile: (options: ExportOptions) => {
      viewerRef.current?.downloadFile(options);
    },
    search: (options: SearchOptions) => {
      return viewerRef.current?.search(options) || [];
    },
    getSelection: () => {
      return viewerRef.current?.getSelection() || null;
    },
    setCellValue: (row: number, col: number, value: any) => {
      viewerRef.current?.setCellValue(row, col, value);
    },
    getCellValue: (row: number, col: number) => {
      return viewerRef.current?.getCellValue(row, col);
    },
    setActiveSheet: (index: number) => {
      viewerRef.current?.setActiveSheet(index);
    },
    undo: () => {
      viewerRef.current?.undo();
    },
    redo: () => {
      viewerRef.current?.redo();
    },
    refresh: () => {
      viewerRef.current?.refresh();
    },
  }));

  // 计算容器样式
  const containerStyle: React.CSSProperties = {
    position: 'relative',
    overflow: 'hidden',
    height: typeof height === 'number' ? `${height}px` : height,
    width: typeof width === 'number' ? `${width}px` : width,
    ...style,
  };

  return (
    <div
      ref={containerRef}
      className={`excel-viewer-react ${className || ''}`}
      style={containerStyle}
    />
  );
});

ExcelViewer.displayName = 'ExcelViewer';
