// packages/lit/src/excel-viewer.ts
/**
 * Excel Viewer Lit Web Component
 */

import { LitElement, html, css } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { ExcelViewer as CoreViewer } from '@ldesign/excel-viewer-core';
import type {
  ExcelViewerOptions,
  SheetData,
  ExportOptions,
  SearchOptions,
  SearchResult,
  SelectionRange,
} from '@ldesign/excel-viewer-core';

/**
 * Excel Viewer Web Component
 * 
 * @element excel-viewer
 * 
 * @fires load - 文件加载完成事件
 * @fires load-error - 文件加载错误事件
 * @fires cell-change - 单元格变化事件
 * @fires cell-click - 单元格点击事件
 * @fires cell-double-click - 单元格双击事件
 * @fires selection-change - 选择区域变化事件
 * @fires sheet-change - 工作表切换事件
 * @fires error - 错误事件
 * 
 * @example
 * ```html
 * <excel-viewer
 *   file-url="./sample.xlsx"
 *   show-toolbar="true"
 *   allow-edit="true"
 *   lang="zh"
 *   height="600px"
 * ></excel-viewer>
 * ```
 */
@customElement('excel-viewer')
export class ExcelViewerElement extends LitElement {
  static styles = css`
    :host {
      display: block;
      position: relative;
      width: 100%;
      height: 600px;
    }

    .excel-viewer-container {
      width: 100%;
      height: 100%;
      position: relative;
      overflow: hidden;
    }

    :host([theme="dark"]) .excel-viewer-container {
      background-color: #1e1e1e;
      color: #ffffff;
    }
  `;

  @query('.excel-viewer-container')
  private container!: HTMLDivElement;

  private viewer: CoreViewer | null = null;

  /** 文件 URL */
  @property({ type: String, attribute: 'file-url' })
  fileUrl?: string;

  /** 是否显示工具栏 */
  @property({ type: Boolean, attribute: 'show-toolbar' })
  showToolbar = true;

  /** 是否显示公式栏 */
  @property({ type: Boolean, attribute: 'show-formula-bar' })
  showFormulaBar = true;

  /** 是否显示表格标签 */
  @property({ type: Boolean, attribute: 'show-sheet-tabs' })
  showSheetTabs = true;

  /** 是否允许编辑 */
  @property({ type: Boolean, attribute: 'allow-edit' })
  allowEdit = true;

  /** 是否允许复制 */
  @property({ type: Boolean, attribute: 'allow-copy' })
  allowCopy = true;

  /** 是否允许粘贴 */
  @property({ type: Boolean, attribute: 'allow-paste' })
  allowPaste = true;

  /** 语言 */
  @property({ type: String })
  lang: 'zh' | 'en' = 'zh';

  /** 主题 */
  @property({ type: String, reflect: true })
  theme: 'light' | 'dark' = 'light';

  /** 容器高度 */
  @property({ type: String })
  height = '600px';

  /** 容器宽度 */
  @property({ type: String })
  width = '100%';

  render() {
    return html`
      <div
        class="excel-viewer-container"
        style="height: ${this.height}; width: ${this.width};"
      ></div>
    `;
  }

  firstUpdated() {
    this.initViewer();
  }

  updated(changedProperties: Map<string, any>) {
    super.updated(changedProperties);

    // 如果 fileUrl 改变，重新加载文件
    if (changedProperties.has('fileUrl') && this.fileUrl && this.viewer) {
      this.loadFile(this.fileUrl);
    }
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.destroyViewer();
  }

  /**
   * 初始化查看器
   */
  private initViewer() {
    if (!this.container) return;

    const options: ExcelViewerOptions = {
      container: this.container,
      showToolbar: this.showToolbar,
      showFormulaBar: this.showFormulaBar,
      showSheetTabs: this.showSheetTabs,
      allowEdit: this.allowEdit,
      allowCopy: this.allowCopy,
      allowPaste: this.allowPaste,
      lang: this.lang,
      theme: this.theme,
      hooks: {
        afterLoad: (data) => {
          this.dispatchEvent(
            new CustomEvent('load', {
              detail: { status: 'success', sheets: data },
              bubbles: true,
              composed: true,
            })
          );
        },
        onCellClick: (sheetIndex, row, col, value) => {
          this.dispatchEvent(
            new CustomEvent('cell-click', {
              detail: { sheetIndex, row, col, value },
              bubbles: true,
              composed: true,
            })
          );
        },
        onCellDoubleClick: (sheetIndex, row, col, value) => {
          this.dispatchEvent(
            new CustomEvent('cell-double-click', {
              detail: { sheetIndex, row, col, value },
              bubbles: true,
              composed: true,
            })
          );
        },
        onSelectionChange: (range) => {
          this.dispatchEvent(
            new CustomEvent('selection-change', {
              detail: range,
              bubbles: true,
              composed: true,
            })
          );
        },
        onError: (error) => {
          this.dispatchEvent(
            new CustomEvent('error', {
              detail: error,
              bubbles: true,
              composed: true,
            })
          );
        },
      },
    };

    this.viewer = new CoreViewer(options);

    // 绑定事件
    this.viewer.on('load', (data) => {
      this.dispatchEvent(
        new CustomEvent('load', {
          detail: data,
          bubbles: true,
          composed: true,
        })
      );
    });

    this.viewer.on('loadError', (data) => {
      this.dispatchEvent(
        new CustomEvent('load-error', {
          detail: data.error,
          bubbles: true,
          composed: true,
        })
      );
    });

    this.viewer.on('cellChange', (data) => {
      this.dispatchEvent(
        new CustomEvent('cell-change', {
          detail: data,
          bubbles: true,
          composed: true,
        })
      );
    });

    this.viewer.on('sheetChange', (data) => {
      this.dispatchEvent(
        new CustomEvent('sheet-change', {
          detail: data,
          bubbles: true,
          composed: true,
        })
      );
    });

    // 如果有初始文件 URL，加载它
    if (this.fileUrl) {
      this.loadFile(this.fileUrl);
    }
  }

  /**
   * 加载文件
   */
  async loadFile(file: File | ArrayBuffer | string): Promise<void> {
    if (!this.viewer) {
      throw new Error('Viewer not initialized');
    }
    await this.viewer.loadFile(file);
  }

  /**
   * 获取数据
   */
  getData(): SheetData[] {
    return this.viewer?.getData() || [];
  }

  /**
   * 导出文件
   */
  exportFile(options: ExportOptions): Blob | null {
    return this.viewer?.exportFile(options) || null;
  }

  /**
   * 下载文件
   */
  downloadFile(options: ExportOptions): void {
    this.viewer?.downloadFile(options);
  }

  /**
   * 搜索
   */
  search(options: SearchOptions): SearchResult[] {
    return this.viewer?.search(options) || [];
  }

  /**
   * 获取选中区域
   */
  getSelection(): SelectionRange | null {
    return this.viewer?.getSelection() || null;
  }

  /**
   * 设置单元格值
   */
  setCellValue(row: number, col: number, value: any): void {
    this.viewer?.setCellValue(row, col, value);
  }

  /**
   * 获取单元格值
   */
  getCellValue(row: number, col: number): any {
    return this.viewer?.getCellValue(row, col);
  }

  /**
   * 切换工作表
   */
  setActiveSheet(index: number): void {
    this.viewer?.setActiveSheet(index);
  }

  /**
   * 撤销
   */
  undo(): void {
    this.viewer?.undo();
  }

  /**
   * 重做
   */
  redo(): void {
    this.viewer?.redo();
  }

  /**
   * 刷新
   */
  refresh(): void {
    this.viewer?.refresh();
  }

  /**
   * 销毁查看器
   */
  private destroyViewer(): void {
    if (this.viewer) {
      this.viewer.destroy();
      this.viewer = null;
    }
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'excel-viewer': ExcelViewerElement;
  }
}

// packages/vue/src/ExcelViewer.vue
<template>
  <div ref="containerRef" class="excel-viewer-vue" :style="containerStyle"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, computed } from 'vue';
import { ExcelViewer } from '@ldesign/excel-viewer-core';
import type {
  ExcelViewerOptions,
  SheetData,
  ExportOptions,
  SearchOptions,
  SearchResult,
  SelectionRange,
} from '@ldesign/excel-viewer-core';

interface Props {
  /** 文件源（File 对象、ArrayBuffer 或 URL） */
  file?: File | ArrayBuffer | string;
  /** 是否显示工具栏 */
  showToolbar?: boolean;
  /** 是否显示公式栏 */
  showFormulaBar?: boolean;
  /** 是否显示表格标签 */
  showSheetTabs?: boolean;
  /** 是否允许编辑 */
  allowEdit?: boolean;
  /** 是否允许复制 */
  allowCopy?: boolean;
  /** 是否允许粘贴 */
  allowPaste?: boolean;
  /** 语言 */
  lang?: 'zh' | 'en';
  /** 主题 */
  theme?: 'light' | 'dark';
  /** 自定义样式 */
  customStyle?: string;
  /** 容器高度 */
  height?: string | number;
  /** 容器宽度 */
  width?: string | number;
}

const props = withDefaults(defineProps<Props>(), {
  showToolbar: true,
  showFormulaBar: true,
  showSheetTabs: true,
  allowEdit: true,
  allowCopy: true,
  allowPaste: true,
  lang: 'zh',
  theme: 'light',
  height: '600px',
  width: '100%',
});

interface Emits {
  (e: 'load', data: { status: string; sheets?: SheetData[] }): void;
  (e: 'loadError', error: any): void;
  (e: 'cellChange', data: { row: number; col: number; oldValue: any; newValue: any }): void;
  (e: 'cellClick', data: { sheetIndex: number; row: number; col: number; value: any }): void;
  (e: 'cellDoubleClick', data: { sheetIndex: number; row: number; col: number; value: any }): void;
  (e: 'selectionChange', range: SelectionRange): void;
  (e: 'sheetChange', data: { index: number }): void;
  (e: 'error', error: any): void;
}

const emit = defineEmits<Emits>();

const containerRef = ref<HTMLElement>();
let viewer: ExcelViewer | null = null;

const containerStyle = computed(() => {
  const style: Record<string, string> = {};
  
  if (typeof props.height === 'number') {
    style.height = `${props.height}px`;
  } else {
    style.height = props.height;
  }
  
  if (typeof props.width === 'number') {
    style.width = `${props.width}px`;
  } else {
    style.width = props.width;
  }
  
  return style;
});

/**
 * 初始化查看器
 */
const initViewer = () => {
  if (!containerRef.value) return;

  const options: ExcelViewerOptions = {
    container: containerRef.value,
    showToolbar: props.showToolbar,
    showFormulaBar: props.showFormulaBar,
    showSheetTabs: props.showSheetTabs,
    allowEdit: props.allowEdit,
    allowCopy: props.allowCopy,
    allowPaste: props.allowPaste,
    lang: props.lang,
    theme: props.theme,
    customStyle: props.customStyle,
    hooks: {
      afterLoad: (data) => {
        emit('load', { status: 'success', sheets: data });
      },
      onCellClick: (sheetIndex, row, col, value) => {
        emit('cellClick', { sheetIndex, row, col, value });
      },
      onCellDoubleClick: (sheetIndex, row, col, value) => {
        emit('cellDoubleClick', { sheetIndex, row, col, value });
      },
      onSelectionChange: (range) => {
        emit('selectionChange', range);
      },
      onError: (error) => {
        emit('error', error);
      },
    },
  };

  viewer = new ExcelViewer(options);

  // 绑定事件
  viewer.on('load', (data) => emit('load', data));
  viewer.on('loadError', (data) => emit('loadError', data.error));
  viewer.on('cellChange', (data) => emit('cellChange', data));
  viewer.on('sheetChange', (data) => emit('sheetChange', data));
  viewer.on('error', (data) => emit('error', data.error));
};

/**
 * 加载文件
 */
const loadFile = async (file: File | ArrayBuffer | string) => {
  if (!viewer) return;
  await viewer.loadFile(file);
};

/**
 * 获取数据
 */
const getData = (): SheetData[] => {
  return viewer?.getData() || [];
};

/**
 * 导出文件
 */
const exportFile = (options: ExportOptions): Blob | null => {
  return viewer?.exportFile(options) || null;
};

/**
 * 下载文件
 */
const downloadFile = (options: ExportOptions): void => {
  viewer?.downloadFile(options);
};

/**
 * 搜索
 */
const search = (options: SearchOptions): SearchResult[] => {
  return viewer?.search(options) || [];
};

/**
 * 获取选中区域
 */
const getSelection = (): SelectionRange | null => {
  return viewer?.getSelection() || null;
};

/**
 * 设置单元格值
 */
const setCellValue = (row: number, col: number, value: any): void => {
  viewer?.setCellValue(row, col, value);
};

/**
 * 获取单元格值
 */
const getCellValue = (row: number, col: number): any => {
  return viewer?.getCellValue(row, col);
};

/**
 * 切换工作表
 */
const setActiveSheet = (index: number): void => {
  viewer?.setActiveSheet(index);
};

/**
 * 撤销
 */
const undo = (): void => {
  viewer?.undo();
};

/**
 * 重做
 */
const redo = (): void => {
  viewer?.redo();
};

/**
 * 刷新
 */
const refresh = (): void => {
  viewer?.refresh();
};

// 监听文件变化
watch(() => props.file, async (newFile) => {
  if (newFile && viewer) {
    await loadFile(newFile);
  }
});

onMounted(() => {
  initViewer();
  
  // 如果有初始文件，加载它
  if (props.file && viewer) {
    loadFile(props.file);
  }
});

onBeforeUnmount(() => {
  if (viewer) {
    viewer.destroy();
    viewer = null;
  }
});

// 暴露方法给父组件
defineExpose({
  loadFile,
  getData,
  exportFile,
  downloadFile,
  search,
  getSelection,
  setCellValue,
  getCellValue,
  setActiveSheet,
  undo,
  redo,
  refresh,
});
</script>

<style scoped>
.excel-viewer-vue {
  position: relative;
  overflow: hidden;
}
</style>
